source 'git@github.com:anfema/anfema-pod-specs.git'
source 'https://github.com/CocoaPods/Specs'

use_frameworks!
platform :ios, '9.0'

def shared_pods
    pod 'Alamofire', '~> 4.7'
    pod 'SQLite.swift', '~> 0.12'
    pod 'HashExtensions', '~> 2.0'
    pod 'DEjson', '~> 4.0'
    pod 'Markdown', :path => '../../'
    pod 'html5tokenizer', '~> 3.0'
    pod 'Tarpit', '~> 3.0'
    pod 'anfema-mockingbird', '~> 4.0'
    pod 'iso-rfc822-date', '~> 1.0'
end

target 'ion-tests' do
  shared_pods
end

target 'ion_client' do
  shared_pods
end

target 'tests' do
  shared_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'Alamofire'
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.2'
      end
    end
  end
end
