source 'git@git.assembla.com:anfema-intern.cocoapods.git'
source 'https://github.com/CocoaPods/Specs'

use_frameworks!

platform :ios, '8.4'
pod 'Alamofire', '~> 3.1'
pod 'HashExtensions', '~> 1.0'
pod 'DEjson', '~> 1.0'
pod 'Markdown', '~> 1.0'
