source 'git@git.assembla.com:anfema-intern.cocoapods.git'
source 'https://github.com/CocoaPods/Specs'

use_frameworks!
platform :osx, '10.10'

target 'Tutorial' do
    pod 'ion-client', git: 'git@github.com:anfema/ion-client-ios.git', branch: 'develop'
end
