source 'git@git.assembla.com:anfema-intern.cocoapods.git'
source 'https://github.com/CocoaPods/Specs'

use_frameworks!

target :ampclient_ios do
	platform :ios, '8.4'
	pod 'HashExtensions', '~> 1.0'
	pod 'Alamofire', '~> 3.1'
	pod 'Markdown', '~> 1.0'
	pod 'DEjson', '~> 1.0'
end

target :ampclient_osx do
	platform :osx, '10.10'
	pod 'HashExtensions', '~> 1.0'
	pod 'Alamofire', '~> 3.1'
	pod 'Markdown', '~> 1.0'
	pod 'DEjson', '~> 1.0'
end

