source 'git@git.assembla.com:anfema-intern.cocoapods.git'
source 'https://github.com/CocoaPods/Specs'

use_frameworks!

platform :osx, '10.10'

def shared_pods
    pod 'Alamofire', '~> 4.2'
    pod 'HashExtensions', '~> 2.0'
    pod 'DEjson', '~> 2.0'
    pod 'Markdown', '~> 2.0'
    pod 'html5tokenizer', '~> 2.0'
    pod 'Tarpit', '~> 2.0'
    pod 'anfema-mockingbird', :git => 'https://github.com/anfema/Mockingbird', :branch => 'swift_3'
    pod 'iso-rfc822-date', '~> 1.0'
end

target 'ion-tests' do
    shared_pods
end

target 'ion_client' do
    shared_pods
end

target 'tests' do
    shared_pods
end
