source 'git@github.com:anfema/anfema-pod-specs.git'
source 'https://github.com/CocoaPods/Specs'

use_frameworks!

platform :osx, '10.12'

def shared_pods
    pod 'Alamofire', '~> 4.7'
    pod 'SQLite.swift', '~> 0.11.5'
    pod 'HashExtensions', '~> 2.0'
    pod 'DEjson', '~> 3.0'
    pod 'Markdown', '~> 3.0'
    pod 'html5tokenizer', '~> 3.0'
    pod 'Tarpit', '~> 2.0'
    
    pod 'anfema-mockingbird', :git => 'https://github.com/anfema/Mockingbird', :branch => 'swift_4'
    pod 'iso-rfc822-date', '~> 1.0'
end

target 'ion-tests' do
    shared_pods
end

target 'ion_client' do
    shared_pods
end

target 'tests' do
    shared_pods
end
